version: '3.7'
services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: api
      dockerfile: Dockerfile
    image: "yape-api:latest"
    ports:
     - "5000:5000"
  web:
    container_name: web
    image: "yape-web:latest"
    build: 
      context: web
      dockerfile: Dockerfile
    ports:
     - "80:80"
