version: '3.7'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    image: "yape-api:latest"
    ports:
     - "5000:5000"
    volumes:
      - yape-data:/data
  web:
    container_name: web
    image: "yape-web:latest"
    build: 
      context: web
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
     - "4200:4200"
volumes:
  yape-data: