apiVersion: v1
kind: Pod
metadata:
  name: yape
spec:
  containers:
  - name: api
    image: yape-api:latest
    ports:
    - containerPort: 5000
  - name: web
    image: yape-web:latest
    ports:
    - containerPort: 80