{{- $fullName := include "yape.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app.kubernetes.io/name: {{ include "yape.name" . }}
    helm.sh/chart: {{ include "yape.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
    - host: yape.local
      http:
        paths:
          - path: /
            backend:
              serviceName: yape-web
              servicePort: http
    - host: api.yape.local
      http:
        paths:
          - path: /
            backend:
              serviceName: yape-api
              servicePort: 5000


