apiVersion: v1
kind: Service
metadata:
  name: {{ include "yape.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "yape.name" . }}-api
    helm.sh/chart: {{ include "yape.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "yape.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
