node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */
        git credentialsId: 'github', url: 'https://github.com/kazamatzuri/yape-web'
    }

    stage('Build api image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        appapi = docker.build("kazamatzuri/yape-api:${env.BUILD_NUMBER}","./api")
        
    }

    stage('Build web image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        appweb = docker.build("kazamatzuri/yape-web:${env.BUILD_NUMBER}","./web")
       
    }

    stage('Push image') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            appapi.push("${env.BUILD_NUMBER}")
            appapi.push("latest")
            appweb.push("${env.BUILD_NUMBER}")
            appweb.push("latest")
        }
    }
}